github.com:
    users:
        aalter237-blip:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: aalter237-blip
