/**
 * Masingar end-to-end encryption (E2EE) — protocol v1.
 *
 * Design
 * ------
 *  • Identity: a long term X25519 key pair per account. The public key is
 *    published through PATCH /api/me, the private key never leaves the device.
 *  • 1:1 messages: X25519 (ephemeral sender key x recipient identity key)
 *    -> HKDF-SHA-256 -> AES-256-GCM. The payload carries only the ephemeral
 *    public key, the nonce and the ciphertext, so the server cannot read it.
 *  • Group messages: one random 32 byte group key generated by the creator and
 *    stored on the server encrypted for every member separately.
 *  • Media: the file is encrypted with its own random key before upload; the
 *    key travels inside the encrypted message body.
 *
 * The wire format of an encrypted message body is base64(JSON):
 *   { v: 1, epk: <b64>, n: <b64>, ct: <b64> }              // 1:1
 *   { v: 1, g: 1, n: <b64>, ct: <b64> }                    // group
 * and the JSON body itself contains: { t: 'text'|'media', x: <text>, m: {...} }
 */

const te = new TextEncoder();
const td = new TextDecoder();

/* ------------------------------- encoding ---------------------------------- */

export function toB64(bytes) {
  const arr = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  let s = '';
  for (let i = 0; i < arr.length; i += 0x8000) s += String.fromCharCode.apply(null, arr.subarray(i, i + 0x8000));
  return btoa(s);
}

export function fromB64(text) {
  const bin = atob(String(text || ''));
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

export const random = (n) => crypto.getRandomValues(new Uint8Array(n));

/* --------------------------- primitive helpers ------------------------------ */

async function hkdf(ikm, salt, info, lengthBytes = 32) {
  const key = await crypto.subtle.importKey('raw', ikm, 'HKDF', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits(
    { name: 'HKDF', hash: 'SHA-256', salt, info: typeof info === 'string' ? te.encode(info) : info },
    key,
    lengthBytes * 8
  );
  return new Uint8Array(bits);
}

async function aesKey(rawBytes) {
  return crypto.subtle.importKey('raw', rawBytes, { name: 'AES-GCM' }, false, ['encrypt', 'decrypt']);
}

async function gcmEncrypt(keyBytes, nonce, plaintext, aad) {
  const key = await aesKey(keyBytes);
  const ct = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv: nonce, additionalData: te.encode(aad || ''), tagLength: 128 },
    key,
    plaintext
  );
  return new Uint8Array(ct);
}

async function gcmDecrypt(keyBytes, nonce, ciphertext, aad) {
  const key = await aesKey(keyBytes);
  const pt = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv: nonce, additionalData: te.encode(aad || ''), tagLength: 128 },
    key,
    ciphertext
  );
  return new Uint8Array(pt);
}

/* --------------------------------- identity --------------------------------- */

const IDENTITY_KEY = 'masingar.identity.v1';

export class Identity {
  constructor(privateKey, publicKey) {
    this.privateKey = privateKey;
    this.publicKey = publicKey;
  }

  static async exportPublic(publicKey) {
    return toB64(await crypto.subtle.exportKey('raw', publicKey));
  }

  static async importPublic(b64) {
    if (!b64) return null;
    try {
      return await crypto.subtle.importKey('raw', fromB64(b64), { name: 'X25519' }, false, []);
    } catch {
      return null;
    }
  }

  /** Loads the local identity, creating one on first use. */
  static async load() {
    const raw = localStorage.getItem(IDENTITY_KEY);
    if (raw) {
      try {
        const obj = JSON.parse(raw);
        const priv = await crypto.subtle.importKey('pkcs8', fromB64(obj.priv), { name: 'X25519' }, true, ['deriveBits']);
        const pub = await crypto.subtle.importKey('raw', fromB64(obj.pub), { name: 'X25519' }, true, []);
        return new Identity(priv, pub);
      } catch {
        /* corrupted -> regenerate below */
      }
    }
    return Identity.create();
  }

  static async create() {
    const pair = await crypto.subtle.generateKey({ name: 'X25519' }, true, ['deriveBits']);
    const identity = new Identity(pair.privateKey, pair.publicKey);
    await identity.persist();
    return identity;
  }

  async persist() {
    const priv = await crypto.subtle.exportKey('pkcs8', this.privateKey);
    const pub = await crypto.subtle.exportKey('raw', this.publicKey);
    localStorage.setItem(IDENTITY_KEY, JSON.stringify({ priv: toB64(priv), pub: toB64(pub) }));
  }

  async publicB64() {
    return Identity.exportPublic(this.publicKey);
  }
}

/** True when the browser can run the protocol (Chrome/Edge/Safari/Firefox 130+). */
export async function isSupported() {
  if (!globalThis.crypto?.subtle) return false;
  try {
    const k = await crypto.subtle.generateKey({ name: 'X25519' }, true, ['deriveBits']);
    return !!k?.privateKey;
  } catch {
    return false;
  }
}

/* --------------------------------- engine ----------------------------------- */

export class CryptoEngine {
  constructor() {
    this.identity = null;
    this.supported = false;
    this.peers = new Map(); // userId -> CryptoKey (public)
    this.peerB64 = new Map(); // userId -> base64 public key
    this.groupKeys = new Map(); // conversationId -> Uint8Array
  }

  async init() {
    this.supported = await isSupported();
    if (!this.supported) return false;
    this.identity = await Identity.load();
    return true;
  }

  async publicKeyB64() {
    if (!this.identity) return '';
    return this.identity.publicB64();
  }

  /** Registers a peer public key (from the conversation / contact payloads). */
  async rememberPeer(userId, b64) {
    if (!b64 || this.peerB64.get(userId) === b64) return this.peers.get(userId) || null;
    const key = await Identity.importPublic(b64);
    if (key) {
      this.peers.set(userId, key);
      this.peerB64.set(userId, b64);
    }
    return key;
  }

  hasPeer(userId) {
    return this.peers.has(userId);
  }

  /* -------------------------------- 1:1 ----------------------------------- */

  async pairwiseKey(peerUserId, conversationId, salt, myId) {
    const peerKey = this.peers.get(peerUserId);
    if (!peerKey || !this.identity) return null;
    const shared = new Uint8Array(
      await crypto.subtle.deriveBits({ name: 'X25519', public: peerKey }, this.identity.privateKey, 256)
    );
    const info = `masingar|v1|${conversationId}|${myId}|${peerUserId}`;
    return hkdf(shared, salt, info, 32);
  }

  /**
   * Encrypts a JSON body for one recipient.
   * Every envelope also carries a copy sealed for ourselves (sn/sct): the
   * ephemeral key is shared, so X25519(our identity, epk) opens it again and
   * our own history stays readable after a reload. Returns null when the peer
   * key is not known yet.
   */
  async encryptDirect({ conversationId, peerId, myId, payload }) {
    if (!this.supported || !this.identity) return null;
    const peerKey = this.peers.get(peerId);
    if (!peerKey) return null;
    const bytes = te.encode(JSON.stringify(payload));
    const eph = await crypto.subtle.generateKey({ name: 'X25519' }, true, ['deriveBits']);
    const ephPub = new Uint8Array(await crypto.subtle.exportKey('raw', eph.publicKey));
    const shared = new Uint8Array(
      await crypto.subtle.deriveBits({ name: 'X25519', public: peerKey }, eph.privateKey, 256)
    );
    const info = `masingar|v1|${conversationId}|${myId}|${peerId}`;
    const key = await hkdf(shared, ephPub, info, 32);
    const nonce = random(12);
    const ct = await gcmEncrypt(key, nonce, bytes, info);

    // X25519(ephemeral, our own identity key): the same secret we will be able
    // to rebuild with X25519(our private key, epk) when we open it later
    const selfInfo = `masingar|v1|${conversationId}|${myId}|${myId}`;
    const selfShared = new Uint8Array(
      await crypto.subtle.deriveBits({ name: 'X25519', public: this.identity.publicKey }, eph.privateKey, 256)
    );
    const selfNonce = random(12);
    const selfKey = await hkdf(selfShared, ephPub, selfInfo, 32);
    const sct = toB64(await gcmEncrypt(selfKey, selfNonce, bytes, selfInfo));
    const sn = toB64(selfNonce);

    return toB64(te.encode(JSON.stringify({ v: 1, epk: toB64(ephPub), n: toB64(nonce), ct: toB64(ct), sn, sct })));
  }

  async decryptDirect({ conversationId, peerId, myId, body }) {
    if (!this.supported || !this.identity) return null;
    let envelope;
    try {
      envelope = JSON.parse(td.decode(fromB64(body)));
    } catch {
      return null;
    }
    if (!envelope || envelope.v !== 1) return null;
    if (envelope.g === 1) return this.decryptGroup({ conversationId, envelope });
    const mine = peerId === myId;
    const nonceB64 = mine ? envelope.sn : envelope.n;
    const ctB64 = mine ? envelope.sct : envelope.ct;
    if (!nonceB64 || !ctB64) return null;
    const ephemeral = await Identity.importPublic(envelope.epk);
    if (!ephemeral) return null;
    const shared = new Uint8Array(
      await crypto.subtle.deriveBits({ name: 'X25519', public: ephemeral }, this.identity.privateKey, 256)
    );
    const info = `masingar|v1|${conversationId}|${peerId}|${myId}`;
    const key = await hkdf(shared, fromB64(envelope.epk), info, 32);
    const plain = await gcmDecrypt(key, fromB64(nonceB64), fromB64(ctB64), info);
    return JSON.parse(td.decode(plain));
  }

  /* -------------------------------- groups --------------------------------- */

  async createGroupKey(conversationId) {
    const key = random(32);
    this.groupKeys.set(conversationId, key);
    return key;
  }

  async wrapGroupKey(conversationId, groupKey, memberId, myId) {
    const peerKey = this.peers.get(memberId);
    if (!peerKey || !this.identity) return null;
    const eph = await crypto.subtle.generateKey({ name: 'X25519' }, true, ['deriveBits']);
    const ephPub = new Uint8Array(await crypto.subtle.exportKey('raw', eph.publicKey));
    const shared = new Uint8Array(
      await crypto.subtle.deriveBits({ name: 'X25519', public: peerKey }, eph.privateKey, 256)
    );
    const info = `masingar|gk1|${conversationId}|${myId}|${memberId}`;
    const key = await hkdf(shared, ephPub, info, 32);
    const nonce = random(12);
    const ct = await gcmEncrypt(key, nonce, groupKey, info);
    return { enc: toB64(ct), nonce: toB64(nonce), epk: toB64(ephPub) };
  }

  /** Unwraps the group key that the creator encrypted for us. */
  async unwrapGroupKey(conversationId, record, myId, creatorId) {
    if (!this.identity || !record?.enc) return null;
    const creatorKey = this.peers.get(creatorId);
    if (!creatorKey) return null;
    const ephemeral = await Identity.importPublic(record.epk);
    if (!ephemeral) return null;
    const shared = new Uint8Array(
      await crypto.subtle.deriveBits({ name: 'X25519', public: ephemeral }, this.identity.privateKey, 256)
    );
    const info = `masingar|gk1|${conversationId}|${creatorId}|${myId}`;
    const key = await hkdf(shared, fromB64(record.epk), info, 32);
    const plain = await gcmDecrypt(key, fromB64(record.nonce), fromB64(record.enc), info);
    this.groupKeys.set(conversationId, plain);
    return plain;
  }

  async encryptGroup({ conversationId, senderId, payload }) {
    const key = this.groupKeys.get(conversationId);
    if (!key) return null;
    const nonce = random(12);
    const info = `masingar|g1|${conversationId}|${senderId}`;
    const ct = await gcmEncrypt(key, nonce, te.encode(JSON.stringify(payload)), info);
    return toB64(te.encode(JSON.stringify({ v: 1, g: 1, n: toB64(nonce), ct: toB64(ct) })));
  }

  async decryptGroup({ conversationId, envelope, senderId = '' }) {
    const key = this.groupKeys.get(conversationId);
    if (!key) return null;
    const info = `masingar|g1|${conversationId}|${senderId}`;
    const plain = await gcmDecrypt(key, fromB64(envelope.n), fromB64(envelope.ct), info);
    return JSON.parse(td.decode(plain));
  }

  /* --------------------------------- media ---------------------------------- */

  /** Encrypts a file before upload. Returns the blob to upload + the key. */
  async encryptFile(file) {
    const key = random(32);
    const nonce = random(12);
    const bytes = new Uint8Array(await file.arrayBuffer());
    const ct = await gcmEncrypt(key, nonce, bytes, 'masingar|media|v1');
    return {
      blob: new Blob([ct], { type: 'application/octet-stream' }),
      key: toB64(key),
      nonce: toB64(nonce),
      name: file.name,
      size: file.size,
      mime: file.type || 'application/octet-stream',
    };
  }

  /** Decrypts a downloaded media blob. */
  async decryptMedia(buffer, keyB64, nonceB64) {
    const plain = await gcmDecrypt(fromB64(keyB64), fromB64(nonceB64), new Uint8Array(buffer), 'masingar|media|v1');
    return plain;
  }

  async mediaUrlFor(message) {
    // returns an object URL for an encrypted (or plain) attachment
    if (!message?.mediaUrl) return null;
    const res = await fetch(message.mediaUrl.startsWith('http') ? message.mediaUrl : message.mediaUrl);
    const buffer = await res.arrayBuffer();
    const meta = message.media || {};
    if (this.supported && meta.k && meta.n) {
      const plain = await this.decryptMedia(buffer, meta.k, meta.n);
      return URL.createObjectURL(new Blob([plain], { type: meta.mime || 'application/octet-stream' }));
    }
    return message.mediaUrl;
  }
}

export const E2EE = new CryptoEngine();
